### ISSUE TITLE
Hello author, can you share the data processing code?

### ISSUE THREAD

**Issue by teacherll** [HuangWBill/DL_LSM#3]

**Comment by HuangWBill** [comment]
Data processing can be done using our toolbox based on ArcGIS software, which I believe will be very useful for your work!
SVM-LSM Toolbox: [Download](https://github.com/HuangWBill/SVM-LSM-Toolbox/). 
Related paper: [An Efficient User-Friendly Integration Tool for Landslide Susceptibility Mapping Based on Support Vector Machines: SVM-LSM Toolbox](https://doi.org/10.3390/rs14143408)
